@Library('accuknox-shared-library@dev') _
pipelineExecute app_config: 'resources/build-info.yaml',
dev_branch: "dev",
verify_branch: "verify",
prod_branch: "prod",
jenkins_node_label: "jenkins-slave-01"